config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'
  
  get 'about' => 'about#index'

  root 'books#index'

  
  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
      @page_title = "About Us"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis quaerat enim neque ipsa beatae fuga, asperiores facilis cum labore iusto soluta nam minus, laboriosam iste officia consectetur a. Placeat, eveniet!</span>
<span>Placeat rem iste dolores, molestias? Ducimus odio quis, eos dolorum blanditiis distinctio, qui sed nesciunt itaque, necessitatibus repellendus. Mollitia, numquam accusamus eveniet itaque, consectetur soluta earum temporibus! Aut, officia, at.</span>
<span>Vitae alias ipsam eligendi possimus expedita, sequi error aut est reiciendis nulla, debitis nesciunt laudantium quisquam ipsa quo eum earum at animi, modi aliquid! Amet id autem dolore quos voluptatibus?</span>
<span>Maxime magni quo beatae fuga excepturi dolores temporibus nesciunt ipsam dignissimos quod. Ducimus cum corporis iste porro laudantium officia, commodi, dignissimos quas, provident atque reiciendis ut repellat praesentium esse culpa.</span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aperiam nisi blanditiis sapiente iure, possimus sint aliquam ut corporis? Recusandae tempore, exercitationem natus hic. Eligendi perferendis molestias ratione, fuga sed.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books-index">
    <div class="row">
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
           <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Power</h3>
            <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg") %>
            <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>


<%= form_for @book do |f| %>
    <div class="form-group">
        <%= f.label :title %> <br>
        <%= f.text_field :title, class: "form-control" %><br>
    </div>
    <div class="form-group">
        <%= f.label :isbn %> <br>
        <%= f.text_field :isb, class: "form-control" %><br>
    </div>
    <div class="form-group">
        <%= f.label :category %><br>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"}, class: "form-control" %><br><br>
    </div>



<% end %>

app/views/books/show.html.erb
<div id="books-show">
    <h2>Ruby on Rails Power</h2>
    <div class="books-show-left">
        <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/51pBROaN%2BlL._SX403_BO1,204,203,200_.jpg", size: "270x400") %>
    </div>
    <div class="books-show-right">
        <h3>Book info:</h3>
        <ul>
            <li><strong>Category: </strong>Ruby on Rails</li>
            <li><strong>Author: </strong>Aneesha Bakharia</li>
            <li><strong>Publisher: </strong>Course Technology PTR</li>
            <li><strong>Year: </strong>2007</li>
            <li><strong>ISBN: </strong>1598632167</li>
            <li><strong>Format: </strong>Paperback</li>
            <li><strong>Pages: </strong>678</li>
        </ul>
        <%= link_to "Buy for $5.97", "http://www.ebay.com/itm/Ruby-on-Rails-Power-The-Comprehensive-Guide-ExLib-/262869524456?epid=50789121&hash=item3d343e9fe8:g:ulMAAOSwr~lYsVWX", class: "btn btn-success", target: "_blank" %>
    </div>
    <div class="clearfix"></div>
        <h4>Excerpt</h4>
        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum tenetur rem veritatis voluptates, perspiciatis, aliquid sit et eius porro amet atque odit, aliquam dolorem est enim perferendis eaque ad architecto?</span>
        <span>Eius sint nisi magnam nemo odit perferendis, ducimus assumenda totam? Quo libero molestias dicta sunt delectus eius numquam, quod dolorum voluptatibus omnis architecto voluptatum harum porro. Expedita sunt, nemo nobis.</span>
        <span>Id iste ipsam explicabo sequi placeat voluptas tenetur voluptate rem! Explicabo quae dicta optio dolorum totam ratione, et perspiciatis veritatis inventore nobis non labore aperiam temporibus earum, a animi, vel?</span>
        <span>Nobis tenetur modi expedita voluptatem ullam pariatur eos velit sed impedit doloribus illo asperiores iusto sapiente, quibusdam deleniti voluptatibus culpa, laborum in blanditiis laudantium, reiciendis. Ipsa fugiat odit magnam ducimus!</span></p>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= @page_title ? @page_title : "Welcome" %> | The BookStore</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to "Home", root_path %></li>
                        <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to "About", about_path %></li>
                        <li class="<%= params[:controller] == 'contact' ? 'active' : '' %>"><a href="#contact">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Book",      new_book_path %></li>
                                <li><%= link_to "Category",  new_category_path %></li>
                                <li><%= link_to "Author",    new_author_path %></li>
                                <li><%= link_to "Publisher", new_publisher_path %></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <header>
            <div class="container">
                <h1>The BookStore <small><%= @page_title ? @page_title : "Welcome" %></small></h1>
            </div>
        </header>
        
        <section>
            <div class="container">
               <div class="row">
                   <div class="col-md-8">
                        <%= yield %>
                   </div>
                   <div class="col-md-4">
                       <%= render "partials/sidebar" %>
                   </div>
               </div>
            </div>
        </section>
        
        <footer>
            <div class="container">
                <p>Copyright &copy; 2014, All Rights Reserved</p>
            </div>
        </footer>

    </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == "about" %>
    <div class="well">
        <h3>Location Info</h3>
        <ul>
            <li>The BookStore</li>
            <li>499 Massachusetts Ave, Unit 3</li>
            <li>Boston, MA, 02110</li>
            <li>Phone: (234) 234-2683</li>
            <li>Email: support@thebookstore.com</li>
        </ul>
    </div>
<% end %>

<% if params[:controller] == "books" && params[:action] == "index" || params[:action] == "show" %>
    <div class="list-group">
        <a href="#" class="list-group-item">Ruby on Rails</a>
        <a href="#" class="list-group-item">PHP</a>
        <a href="#" class="list-group-item">HTML 5</a>
    </div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Publishers#new</h1>
<p>Find me in app/views/publishers/new.html.erb</p>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>